apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: bank-of-anthos-ai-services

build:
  artifacts:
    - image: frontend
      context: src/frontend
    - image: conversational-banking-agent
      context: ai-services/conversational_banking_agent
    - image: transaction-sage
      context: ai-services/transaction-sage
    - image: money-sage
      context: ai-services/money-sage
    - image: contact-sage
      context: ai-services/contact-sage
    - image: transaction-intel
      context: ai-services/transaction-intel
    - image: anomaly-sage
      context: ai-services/anomaly-sage
  local:
    push: false

# Base manifests that are always deployed
manifests:
  rawYaml:
    - kubernetes-manifests/ai-meta-db.yaml
    - kubernetes-manifests/ai-meta-db-init-script.yaml

deploy:
  kubectl: {}

# Profiles allow us to select which service(s) to run
profiles:
  - name: orchestrator
    manifests:
      rawYaml:
        - kubernetes-manifests/conversational-banking-agent.yaml
  - name: transaction-sage
    manifests:
      rawYaml:
        - kubernetes-manifests/transaction-sage.yaml
  - name: money-sage
    manifests:
      rawYaml:
        - kubernetes-manifests/money-sage.yaml
  - name: contact-sage
    manifests:
      rawYaml:
        - kubernetes-manifests/contact-sage.yaml
  - name: transaction-intel
    manifests:
      rawYaml:
        - kubernetes-manifests/transaction-intel.yaml
  - name: anomaly-sage
    manifests:
      rawYaml:
        - kubernetes-manifests/anomaly-sage.yaml
  - name: all-agents
    activation:
      - command: dev # Automatically activate when running skaffold dev
    manifests:
      rawYaml:
        - kubernetes-manifests/conversational-banking-agent.yaml
        - kubernetes-manifests/transaction-sage.yaml
        - kubernetes-manifests/money-sage.yaml
        - kubernetes-manifests/contact-sage.yaml
        - kubernetes-manifests/transaction-intel.yaml
        - kubernetes-manifests/anomaly-sage.yaml