# money-sage.yaml
apiVersion: v1
kind: Service
metadata:
  name: money-sage
spec:
  selector:
    app: money-sage
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-sage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: money-sage
  template:
    metadata:
      labels:
        app: money-sage
    spec:
      containers:
      - name: money-sage
        image: money-sage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: service-api-config
        env:
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-key-secret
              key: public-key.pem
        - name: AI_META_DB_URI
          value: "postgresql://ai-meta-db:ai-meta-db@ai-meta-db:5432/ai-meta-db"
        - name: BALANCE_READER_URL
          value: "http://balancereader:8080"
        - name: TRANSACTION_HISTORY_URL
          value: "http://transactionhistory:8080"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 20