
apiVersion: v1
kind: Service
metadata:
  name: money-sage
spec:
  selector:
    app: money-sage
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-sage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: money-sage
  template:
    metadata:
      labels:
        app: money-sage
    spec:
      containers:
      - name: money-sage
        image: money-sage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://ai-meta-db:ai-meta-db@ai-meta-db:5432/ai-meta-db"
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-key-secret
              key: public-key.pem
        - name: BALANCE_READER_URL
          value: "http://balancereader:8080"
        - name: TRANSACTION_HISTORY_URL
          value: "http://transactionhistory:8086"
        - name: TRANSACTION_SAGE_URL
          value: "http://transaction-sage:8082"
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 8084
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 10
