# orchestrator.yaml
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: orchestrator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: service-api-config
        - configMapRef:
            name: environment-config
        env:
        # --- Gemini API Key ---
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys-secret
              key: gadk-api-key
        - name: EXCHANGE_RATE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys-secret
              key: exchange-rate-api-key
        # --- Database URI ---
        - name: AI_META_DB_URI
          value: "postgresql://ai-meta-db:ai-meta-db@ai-meta-db:5432/ai-meta-db"
        # --- JWT Public Key ---
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-key-secret
              key: public-key.pem
        # --- AI Agent Service URLs ---
        - name: CONTACT_SAGE_URL
          value: "http://contact-sage:8083"
        - name: MONEY_SAGE_URL
          value: "http://money-sage:8084"
        - name: ANOMALY_SAGE_URL
          value: "http://anomaly-sage:8085"
        - name: TRANSACTION_SAGE_URL
          value: "http://transaction-sage:8086"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 20